version: "3.9"
services:
  db:
    restart: always
    image: mysql:5.7.22
    container_name: mysql
    environment:
      MYSQL_DATABASE: image_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33061:3306
    volumes:
      - .mysql:/var/lib/mysql

  backend: &backend
    container_name: django
    command : bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./backend
    volumes:
      - ./backend:/django
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    container_name: react
    build: 
      context: ./frontend
    volumes:
      - ./frontend:/react
      - '/react/node_modules'
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: redis

  celery:
    <<: *backend
    container_name: celery
    ports: []
    command: bash -c "celery -A main beat & celery -A main worker"
    depends_on:
      - redis
      - backend

  url:
    container_name: url
    command : bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    build:
      context: ./url_shortener
    volumes:
      - ./url_shortener:/url
    ports:
      - 8001:8001
    depends_on:
      - db